import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import NavBar from "@/components/nav/NavBar";
import SessionProvider from "@/components/sessions-provider";
import { Toaster } from "@/components/ui/toaster"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark" // dark, light, system
                    enableSystem
                    disableTransitionOnChange
                >
                    <main className="max-w-7xl mx-auto p-10 space-y-10">
                        <NavBar />
                        {children}
                    </main>
                    <Toaster />
                </ThemeProvider>
                <SessionProvider />
            </body>
        </html>
    );
}
